common: &COMMON
  env:
    HOME: /tmp # cargo needs it
    RUST_BACKTRACE: full  # Better info for debugging test failures.
  setup_script:
    - pkg install -y git-lite llvm python
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain ${VERSION}-x86_64-unknown-freebsd
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all
  iostat_script:
    # Run iostat as a smoketest of freebsd-libgeom
    - . $HOME/.cargo/env
    - cargo run --example iostat
  # Until -b works, there's no way to run gstat non-interactively

task:
  env:
    VERSION: 1.57.0
  matrix:
    - name: FreeBSD 14.0-CURRENT MSRV
      freebsd_instance:
        image_family: freebsd-14-0-snap
    - name: FreeBSD 13.1 MSRV
      freebsd_instance:
        image: freebsd-13-1-release-amd64
    - name: FreeBSD 12.3 MSRV
      freebsd_instance:
        image: freebsd-12-3-release-amd64
  << : *COMMON
  before_cache_script: rm -rf $HOME/.cargo/registry/index

task:
  name: FreeBSD 13.1 nightly
  env:
    VERSION: nightly
  freebsd_instance:
    image: freebsd-13-1-release-amd64
  << : *COMMON
  doc_script:
    - . $HOME/.cargo/env
    - cargo doc --all-features --no-deps
  clippy_script:
    - . $HOME/.cargo/env
    - rustup component add clippy
    - cargo clippy --all-features --all-targets -- -D warnings
  audit_script:
    - . $HOME/.cargo/env
    - pkg install -y cargo-audit
    - cargo audit
  # Test our minimal version spec
  minver_test_script:
    # We can't check minver for gstat itself, since confy fails to build with
    # its minium specified versions.  So just check freebsd-libgeom.
    - . $HOME/.cargo/env
    - cd freebsd-libgeom
    - cargo update -Zminimal-versions
    - cargo check --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index

# Ensure that the docs can be cross-compiled, as Cirrus does.
task:
  name: Cross docs
  container:
    image: rustlang/rust:nightly
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  doc_script:
    - rustup target add x86_64-unknown-freebsd
    - cargo doc --target x86_64-unknown-freebsd --no-deps -p freebsd-libgeom-sys -p freebsd-libgeom
  before_cache_script: rm -rf $HOME/.cargo/registry/index
