[workspace]
resolver = "2"
members = [
	"gstat",
	"freebsd-libgeom",
	"freebsd-libgeom-sys",
	"freebsd-geom-exporter"
]

[patch.crates-io]
prometheus_exporter = { git = "https://github.com/AlexanderThaller/prometheus_exporter", rev = "c49efe6" }
