name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - freebsd_version: "13.5"
            rust_version: "1.89.0"
          - freebsd_version: "14.4"
            rust_version: "1.89.0"
          - freebsd_version: "15.0"
            rust_version: "1.89.0"
          - freebsd_version: "14.4"
            rust_version: "nightly"
    name: FreeBSD ${{ matrix.freebsd_version }} ${{ matrix.rust_version }}
    steps:
      - uses: actions/checkout@v6
      - name: Start VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.freebsd_version }}
          usesh: true
      - name: Install dependencies
        shell: freebsd {0}
        run: |
          pkg install -y curl llvm
          fetch https://sh.rustup.rs -o rustup.sh
          sh rustup.sh -y --profile=minimal --default-toolchain ${{ matrix.rust_version }}
      - name: Build
        shell: freebsd {0}
        run: |
          . $HOME/.cargo/env
          cargo build --all
      - name: Test
        shell: freebsd {0}
        run: |
          . $HOME/.cargo/env
          cargo test --all
      - name: Iostat
        shell: freebsd {0}
        run: |
          . $HOME/.cargo/env
          cargo run --example iostat
      - name: Doc
        if: matrix.rust_version == 'nightly'
        shell: freebsd {0}
        run: |
          . $HOME/.cargo/env
          cargo doc --no-deps
      - name: Clippy
        if: matrix.rust_version == 'nightly'
        shell: freebsd {0}
        run: |
          . $HOME/.cargo/env
          rustup component add clippy
          cargo clippy --all-targets -- -D warnings
      - name: Audit
        if: matrix.rust_version == 'nightly'
        shell: freebsd {0}
        run: |
          . $HOME/.cargo/env
          pkg install -y cargo-audit
          cargo audit
      - name: Minver
        if: matrix.rust_version == 'nightly'
        shell: freebsd {0}
        run: |
          . $HOME/.cargo/env
          cargo update -Zdirect-minimal-versions
          # Workaround a ratatui bug.
          # Cargo update -Zdirect-minimal-versions downgrades serde, which is a
          # direct dependency.  But time-0.3.27 and later require serde-0.1.184
          # or later.  So time must be downgraded too.  But ratatui-widgets
          # miss-specifies its time dependency as 0.3, even though it really
          # needs 0.3.37.  So the build fails.  Fix it by upgrading time after
          # downgrading everything else.
          # https://github.com/ratatui/ratatui/pull/2306
          cargo update -p time
          cargo check
      - name: Fmt
        if: matrix.rust_version == 'nightly'
        shell: freebsd {0}
        run: |
          . $HOME/.cargo/env
          rustup component add rustfmt
          cargo fmt --all -- --check --color=never

  cross-docs:
    name: Cross docs
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly
    steps:
      - uses: actions/checkout@v6
      - name: Cross compile docs
        run: |
          rustup target add x86_64-unknown-freebsd
          cargo doc --target x86_64-unknown-freebsd --no-deps -p freebsd-libgeom-sys -p freebsd-libgeom
